name: Geodata CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Geodata files
      run: rm -f geodata/*.txt 
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USER }}
        SOURCE: "geodata/"
        TARGET: ${{ secrets.TARGET }}
        SCRIPT_BEFORE: |
          ls -al
        SCRIPT_AFTER: |
          ls -al
          echo $RSYNC_STDOUT